baseURL: "www.arunneru.com"
languageCode: en-us
title: Arun Neru
theme: paperesque

params:
  homeInfoParams:
    Title: My blog is here
    Content: Posts on technology and storytelling
  menu:
    - name: blog
      url: posts/
    - name: tags
      url: tags/
    - name: about
      url: about/
    - name: contact
      url: contact/

